# Generated by Django 2.1.5 on 2019-02-12 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('wechat_id', models.CharField(max_length=10)),
                ('introduction', models.CharField(max_length=100)),
                ('last_updated', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=125)),
                ('description', models.CharField(max_length=340, null=True)),
                ('text_url', models.URLField(max_length=255)),
                ('text', models.TextField(null=True)),
                ('publication_date', models.DateField()),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_mzxl.Account')),
            ],
        ),
    ]
