# Generated by Django 2.1.5 on 2019-02-12 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_mzxl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='introduction',
            field=models.CharField(max_length=200),
        ),
    ]
